version: '3'

services:
  goaws: 
    image: pafortin/goaws
    container_name: goaws
    ports: 
      - 4100:4100
    environment:
      - AWS_ACCESS_KEY_ID=YOU_AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=YOU_AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_DEFAULT_OUTPUT=json
