version: '3'

services:
  goaws: 
    image: pafortin/goaws
    container_name: goaws
    ports: 
      - 4100:4100
    environment:
      - AWS_ACCESS_KEY_ID=${ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${REGION}
      - AWS_DEFAULT_OUTPUT=json
